- src/test/java/uk/co/sleonard/unison/utils/tests/StringUtilsTest.java
You can view my test case?
Thanks!
> StringUtils Test Case

- pom.xml
- src/test/java/uk/co/sleonard/unison/datahandling/tests/DataQueryTest.java
Hi Steve,
I don't find how to mock Session attribute, for the test methods getLocations and getMessages
> Create DataQuery Test

- src/main/java/uk/co/sleonard/unison/datahandling/DAO/EmailAddress.java
- src/main/java/uk/co/sleonard/unison/datahandling/DataQuery.java
- src/main/java/uk/co/sleonard/unison/datahandling/UsenetUserHelper.java
- src/test/java/uk/co/sleonard/unison/datahandling/tests/DataQueryTest.java
- src/test/java/uk/co/sleonard/unison/datahandling/tests/UsenetUserHelperTest.java
Hi Steve,
I removed Main on the UsenetUserHelper, I think is not needed because the test case been created, and override equals on Message to use assertEquals ok?
Thanks!
> Created UsenetUserHelperTest and included test method getMessages

- src/test/java/uk/co/sleonard/unison/datahandling/tests/HibernateHelperTest.java
Hi Steve,
I will continue on development of the class.
If you have any tips for me, I would be grateful.
Thank you!
> Created HibernateHelperTest

- src/main/java/uk/co/sleonard/unison/gui/generated/DownloadNewsPanel.java
- src/main/java/uk/co/sleonard/unison/utils/StringUtils.java
- src/main/resources/servers.properties
- src/test/java/uk/co/sleonard/unison/input/tests/NewsArticleTest.java
#36 
Steve, I improve server list to properties file. I no run the tracker(upwork) in it, I want  really contribute also, not only work .
Ok?, check later, Thanks!
> Improve NewsArticleTest and put nntp server list on servers.properties

- src/test/java/uk/co/sleonard/unison/datahandling/tests/DataQueryTest.java
- src/test/java/uk/co/sleonard/unison/datahandling/tests/HibernateHelperTest.java
- src/test/java/uk/co/sleonard/unison/input/tests/FullDownloadWorkerTest.java
- src/test/java/uk/co/sleonard/unison/input/tests/HeaderDownloadWorkerTest.java
- src/test/java/uk/co/sleonard/unison/input/tests/NNTPNewsGroupTest.java
- src/test/java/uk/co/sleonard/unison/input/tests/NewsGroupReaderTest.java
Hi Steve,
I'm with small difficulty to tests the classes FullDownloadWorker/HeaderDownloadWorker, looks need refactor I do not know, or then I do not know some resource to test the classes or then expertise. If you can give me tips, I stay grateful.
Thank you.
Regards.
> Improve Tests

- pom.xml
- src/test/java/uk/co/sleonard/unison/input/tests/HeaderDownloadWorkerTest.java
Update powermock version from 1.6.1 to 1.6.5 and mockito from 1.9.5 to 1.10.15 
Issue #55 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/leonarduk/unison/58)
> Update powermock version in POM.xml

- src/main/java/uk/co/sleonard/unison/gui/JSplashScreen.java
- src/main/java/uk/co/sleonard/unison/input/SwingWorker.java
- src/test/java/uk/co/sleonard/unison/datahandling/DAO/tests/DownloadRequestTest.java
- src/test/java/uk/co/sleonard/unison/datahandling/DAO/tests/EmailAddressTest.java
- src/test/java/uk/co/sleonard/unison/datahandling/DAO/tests/IpAddressTest.java
- src/test/java/uk/co/sleonard/unison/datahandling/DAO/tests/LocationTest.java
- src/test/java/uk/co/sleonard/unison/datahandling/DAO/tests/MessageTest.java
- src/test/java/uk/co/sleonard/unison/datahandling/DAO/tests/NewsGroupTest.java
- src/test/java/uk/co/sleonard/unison/datahandling/DAO/tests/ResultRowTest.java
- src/test/java/uk/co/sleonard/unison/datahandling/DAO/tests/TopicTest.java
- src/test/java/uk/co/sleonard/unison/datahandling/DAO/tests/UsenetUserTest.java
- src/test/java/uk/co/sleonard/unison/datahandling/tests/DataQueryTest.java
- src/test/java/uk/co/sleonard/unison/datahandling/tests/HibernateHelperTest.java
- src/test/java/uk/co/sleonard/unison/datahandling/tests/UsenetUserHelperTest.java
- src/test/java/uk/co/sleonard/unison/input/tests/FullDownloadWorkerTest.java
- src/test/java/uk/co/sleonard/unison/input/tests/HeaderDownloadWorkerTest.java
- src/test/java/uk/co/sleonard/unison/input/tests/NNTPNewsGroupTest.java
- src/test/java/uk/co/sleonard/unison/input/tests/NewsArticleTest.java
- src/test/java/uk/co/sleonard/unison/input/tests/NewsGroupReaderTest.java
- src/test/java/uk/co/sleonard/unison/output/tests/ExportToCSVTest.java
- src/test/java/uk/co/sleonard/unison/output/tests/PajekNetworkFileTest.java
- src/test/java/uk/co/sleonard/unison/output/tests/RelationshipTest.java
- src/test/java/uk/co/sleonard/unison/utils/tests/StringUtilsTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/leonarduk/unison/66)
> Small adjust on commentaries

- src/main/java/uk/co/sleonard/unison/input/HeaderDownloadWorker.java
- src/main/java/uk/co/sleonard/unison/utils/HttpDateObject.java
- src/test/java/uk/co/sleonard/unison/input/tests/UNISoNCLI.java
The issues were resolved, but some errors in equals method generated by eclipse is showed as error. We change this or not?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/leonarduk/unison/68)
> Refactor Issues of codacy #59

- src/main/java/uk/co/sleonard/unison/utils/HttpDateObject.java
- src/test/java/uk/co/sleonard/unison/datahandling/DAO/tests/IpAddressTest.java
- src/test/java/uk/co/sleonard/unison/datahandling/DAO/tests/LocationTest.java
- src/test/java/uk/co/sleonard/unison/datahandling/DAO/tests/MessageTest.java
- src/test/java/uk/co/sleonard/unison/datahandling/DAO/tests/NewsGroupTest.java
- src/test/java/uk/co/sleonard/unison/datahandling/DAO/tests/TopicTest.java
- src/test/java/uk/co/sleonard/unison/datahandling/DAO/tests/UsenetUserTest.java
- src/test/java/uk/co/sleonard/unison/gui/tests/GUIItemTest.java
- src/test/java/uk/co/sleonard/unison/gui/tests/SimpleFileFilterTest.java
- src/test/java/uk/co/sleonard/unison/gui/tests/TreeNodeTest.java
- src/test/java/uk/co/sleonard/unison/input/tests/NNTPNewsGroupTest.java
- src/test/java/uk/co/sleonard/unison/output/tests/RelationshipTest.java
- src/test/java/uk/co/sleonard/unison/utils/tests/HttpDateObjectTest.java
- src/test/java/uk/co/sleonard/unison/utils/tests/StringUtilsTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/leonarduk/unison/69)
> #5 Improve test coverage

- src/main/java/uk/co/sleonard/unison/datahandling/DataQuery.java
- src/main/java/uk/co/sleonard/unison/input/NewsGroupReader.java
- src/test/java/uk/co/sleonard/unison/input/tests/NewsGroupReaderTest.java
Hi Steve,
I removed the main of NewsGroupReader because the same test is made by you in src/it/java/... NewsClient.java
I am with difficult to create more tests, because some methods perform connections/showing gui or have too much dependency of other classes. The package (input) is a exemple. 
I do not know if some classes need refactor to the unit test be realized. Maybe I need more tools and expertise to create more, I bought the book  JUnit in Action 2nd Edition (Manning) to learn more about the tests.
I should have a capacity to analyse and verify if classes need refactor as a Unit Tester?
You can talk me if my difficulty is normal in your project ? Maybe because your project is somewhat old and the classes have much dependency between them (classes). Or because I am still to …
> #5 Improve tests

- src/test/java/uk/co/sleonard/unison/datahandling/DAO/EmailAddressTest.java
in your last changes, I saw this test that I have created before your tips, then I improved.
Thanks =)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/leonarduk/unison/94)
> fix hashcode test

- src/main/java/uk/co/sleonard/unison/input/LocationFinderImpl.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/leonarduk/unison/98)
> Create a regex to ip address

- src/test/java/uk/co/sleonard/unison/input/LocationFinderImplTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/leonarduk/unison/99)
> Adjust in test, for to cover my last change.

- src/main/java/uk/co/sleonard/unison/utils/Downloader.java
- src/main/java/uk/co/sleonard/unison/utils/DownloaderImpl.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/leonarduk/unison/103)
> #5 add missing files

- src/main/java/uk/co/sleonard/unison/UNISoNControllerFX.java
- src/main/java/uk/co/sleonard/unison/gui/generated/DownloadNewsPanelFX.java
- src/main/java/uk/co/sleonard/unison/gui/generated/UNISoNTabbedFrameFX.java
- src/main/java/uk/co/sleonard/unison/gui/generated/fxml/AboutDialogLayout.fxml
- src/main/java/uk/co/sleonard/unison/gui/generated/fxml/DownloadNewsPanelLayout.fxml
- src/main/java/uk/co/sleonard/unison/gui/generated/fxml/MessageStoreViewerLayout.fxml
- src/main/java/uk/co/sleonard/unison/gui/generated/fxml/PajekPanelLayout.fxml
- src/main/java/uk/co/sleonard/unison/gui/generated/fxml/RootLayout.fxml
I created all FXML of the program.
Call of some methods (exit and about window).
No consider this additions as a final structure, I maybe change the architeture of calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/leonarduk/unison/108)
> #8 - Improve the Gui.

- src/main/java/uk/co/sleonard/unison/datahandling/DAO/NewsGroup.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/leonarduk/unison/115)
> #112 set full name

- src/it/java/uk/co/sleonard/unison/UNISoNControllerIT.java
- src/it/java/uk/co/sleonard/unison/gui/generated/DownloadNewsPanelIT.java
- src/main/java/uk/co/sleonard/unison/UNISoNController.java
- src/main/java/uk/co/sleonard/unison/gui/generated/DownloadNewsPanel.java
- src/main/java/uk/co/sleonard/unison/input/DataHibernator.java
- src/main/java/uk/co/sleonard/unison/input/DataHibernatorImpl.java
- src/main/java/uk/co/sleonard/unison/input/DataHibernatorPool.java
- src/main/java/uk/co/sleonard/unison/input/DataHibernatorPoolImpl.java
- src/test/java/uk/co/sleonard/unison/UNISoNControllerTest.java
- src/test/java/uk/co/sleonard/unison/input/NewsClientTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/leonarduk/unison/116)
> #5 checkpoint

- src/main/java/uk/co/sleonard/unison/UNISoNController.java
- src/main/java/uk/co/sleonard/unison/input/NewsGroupReader.java
- src/test/java/uk/co/sleonard/unison/UNISoNControllerTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/leonarduk/unison/117)
> #5 update coverage

- src/main/java/uk/co/sleonard/unison/UNISoNController.java
- src/main/java/uk/co/sleonard/unison/datahandling/DataQuery.java
- src/main/java/uk/co/sleonard/unison/datahandling/UNISoNDatabase.java
- src/main/java/uk/co/sleonard/unison/gui/generated/PajekPanel.java
- src/test/java/uk/co/sleonard/unison/datahandling/UNISoNDatabaseTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/leonarduk/unison/118)
> #5 add more tests

- pom.xml
- src/test/java/uk/co/sleonard/unison/utils/StringUtilsTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/leonarduk/unison/287)
> fix: stabilize compression test
